name: Run cfrcams.py Every Minute

on:
  schedule:
    - cron: '*/1 * * * *' # This cron schedule triggers the workflow every minute

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace 'x' with the specific Python version you need

    - name: Run Python script
      run: python cfrcams.py
